name: Deploy n8n to Fly.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Fly CLI
        run: curl -L https://fly.io/install.sh | sh
      - name: Authenticate to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: fly auth token $FLY_API_TOKEN
      - name: Set n8n secrets
        run: |
          fly secrets set N8N_BASIC_AUTH_USER=${{ secrets.N8N_USER }}
          fly secrets set N8N_BASIC_AUTH_PASSWORD=${{ secrets.N8N_PASS }}
          fly secrets set WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}
      - name: Deploy
        run: fly deploy
