FROM n8nio/n8n:latest

ENV N8N_PORT=$PORT
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=http

ENV N8N_GIT_NODE_DISABLE_BARE_REPOS=true
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV GENERIC_TIMEZONE="Asia/Almaty"

VOLUME /home/node/.n8n

EXPOSE 5678

CMD ["n8n", "start"]
